version: '3'
services:
    muck-service:
        image: muck/service:0.0.1-SNAPSHOT
        ports:
            - "127.0.0.1:8080:8080"
    muck-webapp:
        image: muck/webapp:0.0.1-SNAPSHOT
        ports: 
            - "127.0.0.1:8000:80"
