version: '3'
services:
    muck-neo4j:
        image: neo4j:3.4.5
        environment:
            - NEO4J_dbms_security_auth__enabled=false
            - NEO4J_dbms_logs_debug_level=DEBUG
        ports:
            - "127.0.0.1:7474:7474"
            - "127.0.0.1:7687:7687"
    muck-service:
        image: muck/service:0.0.1-SNAPSHOT
        links:
            - muck-neo4j:neo4j
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            - NEO4J_URI=bolt://neo4j:7687
    muck-webapp:
        image: muck/webapp:0.0.1-SNAPSHOT
        ports: 
            - "127.0.0.1:8000:80"
