# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - maven-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - maven-dependencies-

      - setup_remote_docker

      - run: 
          name: "Build and test project"
          command: |
              mvn clean install -B

      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: "Build and run E2E Tests"
          command: |
              mvn install -DskipTests -Pdocker
              docker-compose -f docker-compose-e2e.yml up --exit-code-from=muck-e2e --force-recreate
